// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdCjO2PufD5uiWWZAtHHECofKmm8LNKF8',
    appId: '1:910192061668:web:47686ccd9ad570691250f1',
    messagingSenderId: '910192061668',
    projectId: 'new-chat-app-2663a',
    authDomain: 'new-chat-app-2663a.firebaseapp.com',
    storageBucket: 'new-chat-app-2663a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMrtXSbKo-4r0MHUyiBhXtnK3790hAG88',
    appId: '1:910192061668:android:86647a00931be9e71250f1',
    messagingSenderId: '910192061668',
    projectId: 'new-chat-app-2663a',
    storageBucket: 'new-chat-app-2663a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAbqKRks4fIl_oDy26eNM32ah8i_HVCHM',
    appId: '1:910192061668:ios:74eefe53101aa82c1250f1',
    messagingSenderId: '910192061668',
    projectId: 'new-chat-app-2663a',
    storageBucket: 'new-chat-app-2663a.appspot.com',
    iosClientId: '910192061668-vvb70hg3k70ooc9i29hdkdr1nnvpc6hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppNew',
  );
}
